name: update-rates

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo with write permissions
    - uses: actions/checkout@v3
      with:
        persist-credentials: false  # important! so we can use token
        fetch-depth: 0

    # 2. Setup Node.js
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Run archive generation
    - name: Generate archive
      run: node generator/generateArchives.js

    # 4. Run page generation
    - name: Generate pages
      run: node generator/generatePages.js

    # 5. Run sitemap generator
    - name: Generate sitemap
      run: node generator/sitemapGenerator.js

    # Generate static homepage
    - name: Generate index page
      run: node generator/generateIndex.js

    # 6. Commit and push changes
    - name: Commit generated files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git add archives pages seo index.html

        git diff --cached --quiet || git commit -m "Daily update: archives, pages, sitemap"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
